name: "Setup JavaScript"
description: "Setup JavaScript dependencies"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - run: pnpm install --frozen-lockfile
      shell: bash
